Update read_mod.py for mcnp5 and tally8
Hi , i download release file and chose directory but it couldnt detect my mcnp5 outputs and tally 8 , and show me error like this "Name off processed file:  o007.out
Traceback (most recent call last):
  File "D:\Downloads\Compressed\MCNP_TallyPlotter-0.8.4\MCNP_TallyPlotter-0.8.4\modules\read_mod.py", line 250, in read_tally
    if energy[0] > cutoff_en:
                   ^^^^^^^^^
UnboundLocalError: cannot access local variable 'cutoff_en' where it is not associated with a value
Read process crash for this file: o007.out"
so with hlep of git copliot i solved this problem and now to works with my mcnp5 outputs but i dont know why original developer disabled some codes for tally 8 , i enabled one of them also so the fix work, the next codes for tally 8 still disabled.